//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SeeYouOnServiceBL.TMSPhoneBook {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PhoneBookServiceSoap", Namespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TMSIntId))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TMSLongId))]
    public partial class PhoneBookService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback PingOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPhoneBooksOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSourcesForPhoneBookOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreatePhoneBookOperationCompleted;
        
        private System.Threading.SendOrPostCallback RenamePhoneBookOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeletePhoneBookOperationCompleted;
        
        private System.Threading.SendOrPostCallback MovePhoneBookOperationCompleted;
        
        private System.Threading.SendOrPostCallback BindSourceToPhoneBookOperationCompleted;
        
        private System.Threading.SendOrPostCallback UnbindSourceFromPhoneBookOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSourcesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSourceParametersOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteSourceOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateSourceOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateSourceOperationCompleted;
        
        private System.Threading.SendOrPostCallback RenameSourceOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchPhoneBookSourceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPhoneBookSourceContactsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateContactOperationCompleted;
        
        private System.Threading.SendOrPostCallback RenameContactOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteContactOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateContactMethodOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteContactMethodOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddPhoneBookToSystemOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddSystemsToPhoneBookOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemovePhoneBooksFromSystemOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveSystemsFromPhoneBookOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPhoneBooksForSystemOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTmsServerInfoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PhoneBookService() {
            this.Url = global::SeeYouOnServiceBL.Properties.Settings.Default.SeeYouOnServiceBL_TMSPhoneBook_PhoneBookService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event PingCompletedEventHandler PingCompleted;
        
        /// <remarks/>
        public event GetPhoneBooksCompletedEventHandler GetPhoneBooksCompleted;
        
        /// <remarks/>
        public event GetSourcesForPhoneBookCompletedEventHandler GetSourcesForPhoneBookCompleted;
        
        /// <remarks/>
        public event CreatePhoneBookCompletedEventHandler CreatePhoneBookCompleted;
        
        /// <remarks/>
        public event RenamePhoneBookCompletedEventHandler RenamePhoneBookCompleted;
        
        /// <remarks/>
        public event DeletePhoneBookCompletedEventHandler DeletePhoneBookCompleted;
        
        /// <remarks/>
        public event MovePhoneBookCompletedEventHandler MovePhoneBookCompleted;
        
        /// <remarks/>
        public event BindSourceToPhoneBookCompletedEventHandler BindSourceToPhoneBookCompleted;
        
        /// <remarks/>
        public event UnbindSourceFromPhoneBookCompletedEventHandler UnbindSourceFromPhoneBookCompleted;
        
        /// <remarks/>
        public event GetSourcesCompletedEventHandler GetSourcesCompleted;
        
        /// <remarks/>
        public event GetSourceParametersCompletedEventHandler GetSourceParametersCompleted;
        
        /// <remarks/>
        public event DeleteSourceCompletedEventHandler DeleteSourceCompleted;
        
        /// <remarks/>
        public event CreateSourceCompletedEventHandler CreateSourceCompleted;
        
        /// <remarks/>
        public event UpdateSourceCompletedEventHandler UpdateSourceCompleted;
        
        /// <remarks/>
        public event RenameSourceCompletedEventHandler RenameSourceCompleted;
        
        /// <remarks/>
        public event SearchPhoneBookSourceCompletedEventHandler SearchPhoneBookSourceCompleted;
        
        /// <remarks/>
        public event GetPhoneBookSourceContactsCompletedEventHandler GetPhoneBookSourceContactsCompleted;
        
        /// <remarks/>
        public event CreateContactCompletedEventHandler CreateContactCompleted;
        
        /// <remarks/>
        public event RenameContactCompletedEventHandler RenameContactCompleted;
        
        /// <remarks/>
        public event DeleteContactCompletedEventHandler DeleteContactCompleted;
        
        /// <remarks/>
        public event CreateContactMethodCompletedEventHandler CreateContactMethodCompleted;
        
        /// <remarks/>
        public event DeleteContactMethodCompletedEventHandler DeleteContactMethodCompleted;
        
        /// <remarks/>
        public event AddPhoneBookToSystemCompletedEventHandler AddPhoneBookToSystemCompleted;
        
        /// <remarks/>
        public event AddSystemsToPhoneBookCompletedEventHandler AddSystemsToPhoneBookCompleted;
        
        /// <remarks/>
        public event RemovePhoneBooksFromSystemCompletedEventHandler RemovePhoneBooksFromSystemCompleted;
        
        /// <remarks/>
        public event RemoveSystemsFromPhoneBookCompletedEventHandler RemoveSystemsFromPhoneBookCompleted;
        
        /// <remarks/>
        public event GetPhoneBooksForSystemCompletedEventHandler GetPhoneBooksForSystemCompleted;
        
        /// <remarks/>
        public event GetTmsServerInfoCompletedEventHandler GetTmsServerInfoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tandberg.com/TMS/PhoneBookService/1.0/Ping", RequestNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", ResponseNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Ping() {
            object[] results = this.Invoke("Ping", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PingAsync() {
            this.PingAsync(null);
        }
        
        /// <remarks/>
        public void PingAsync(object userState) {
            if ((this.PingOperationCompleted == null)) {
                this.PingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPingOperationCompleted);
            }
            this.InvokeAsync("Ping", new object[0], this.PingOperationCompleted, userState);
        }
        
        private void OnPingOperationCompleted(object arg) {
            if ((this.PingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PingCompleted(this, new PingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tandberg.com/TMS/PhoneBookService/1.0/GetPhoneBooks", RequestNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", ResponseNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PhoneBook[] GetPhoneBooks() {
            object[] results = this.Invoke("GetPhoneBooks", new object[0]);
            return ((PhoneBook[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPhoneBooksAsync() {
            this.GetPhoneBooksAsync(null);
        }
        
        /// <remarks/>
        public void GetPhoneBooksAsync(object userState) {
            if ((this.GetPhoneBooksOperationCompleted == null)) {
                this.GetPhoneBooksOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPhoneBooksOperationCompleted);
            }
            this.InvokeAsync("GetPhoneBooks", new object[0], this.GetPhoneBooksOperationCompleted, userState);
        }
        
        private void OnGetPhoneBooksOperationCompleted(object arg) {
            if ((this.GetPhoneBooksCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPhoneBooksCompleted(this, new GetPhoneBooksCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tandberg.com/TMS/PhoneBookService/1.0/GetSourcesForPhoneBook", RequestNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", ResponseNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PhoneBookToSourceBinding[] GetSourcesForPhoneBook(int PhoneBookId) {
            object[] results = this.Invoke("GetSourcesForPhoneBook", new object[] {
                        PhoneBookId});
            return ((PhoneBookToSourceBinding[])(results[0]));
        }
        
        /// <remarks/>
        public void GetSourcesForPhoneBookAsync(int PhoneBookId) {
            this.GetSourcesForPhoneBookAsync(PhoneBookId, null);
        }
        
        /// <remarks/>
        public void GetSourcesForPhoneBookAsync(int PhoneBookId, object userState) {
            if ((this.GetSourcesForPhoneBookOperationCompleted == null)) {
                this.GetSourcesForPhoneBookOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSourcesForPhoneBookOperationCompleted);
            }
            this.InvokeAsync("GetSourcesForPhoneBook", new object[] {
                        PhoneBookId}, this.GetSourcesForPhoneBookOperationCompleted, userState);
        }
        
        private void OnGetSourcesForPhoneBookOperationCompleted(object arg) {
            if ((this.GetSourcesForPhoneBookCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSourcesForPhoneBookCompleted(this, new GetSourcesForPhoneBookCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tandberg.com/TMS/PhoneBookService/1.0/CreatePhoneBook", RequestNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", ResponseNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PhoneBook CreatePhoneBook(string Name, int ParentPhoneBookId) {
            object[] results = this.Invoke("CreatePhoneBook", new object[] {
                        Name,
                        ParentPhoneBookId});
            return ((PhoneBook)(results[0]));
        }
        
        /// <remarks/>
        public void CreatePhoneBookAsync(string Name, int ParentPhoneBookId) {
            this.CreatePhoneBookAsync(Name, ParentPhoneBookId, null);
        }
        
        /// <remarks/>
        public void CreatePhoneBookAsync(string Name, int ParentPhoneBookId, object userState) {
            if ((this.CreatePhoneBookOperationCompleted == null)) {
                this.CreatePhoneBookOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreatePhoneBookOperationCompleted);
            }
            this.InvokeAsync("CreatePhoneBook", new object[] {
                        Name,
                        ParentPhoneBookId}, this.CreatePhoneBookOperationCompleted, userState);
        }
        
        private void OnCreatePhoneBookOperationCompleted(object arg) {
            if ((this.CreatePhoneBookCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreatePhoneBookCompleted(this, new CreatePhoneBookCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tandberg.com/TMS/PhoneBookService/1.0/RenamePhoneBook", RequestNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", ResponseNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RenamePhoneBook(int PhoneBookId, string Name) {
            this.Invoke("RenamePhoneBook", new object[] {
                        PhoneBookId,
                        Name});
        }
        
        /// <remarks/>
        public void RenamePhoneBookAsync(int PhoneBookId, string Name) {
            this.RenamePhoneBookAsync(PhoneBookId, Name, null);
        }
        
        /// <remarks/>
        public void RenamePhoneBookAsync(int PhoneBookId, string Name, object userState) {
            if ((this.RenamePhoneBookOperationCompleted == null)) {
                this.RenamePhoneBookOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRenamePhoneBookOperationCompleted);
            }
            this.InvokeAsync("RenamePhoneBook", new object[] {
                        PhoneBookId,
                        Name}, this.RenamePhoneBookOperationCompleted, userState);
        }
        
        private void OnRenamePhoneBookOperationCompleted(object arg) {
            if ((this.RenamePhoneBookCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RenamePhoneBookCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tandberg.com/TMS/PhoneBookService/1.0/DeletePhoneBook", RequestNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", ResponseNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeletePhoneBook(int PhoneBookId) {
            this.Invoke("DeletePhoneBook", new object[] {
                        PhoneBookId});
        }
        
        /// <remarks/>
        public void DeletePhoneBookAsync(int PhoneBookId) {
            this.DeletePhoneBookAsync(PhoneBookId, null);
        }
        
        /// <remarks/>
        public void DeletePhoneBookAsync(int PhoneBookId, object userState) {
            if ((this.DeletePhoneBookOperationCompleted == null)) {
                this.DeletePhoneBookOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeletePhoneBookOperationCompleted);
            }
            this.InvokeAsync("DeletePhoneBook", new object[] {
                        PhoneBookId}, this.DeletePhoneBookOperationCompleted, userState);
        }
        
        private void OnDeletePhoneBookOperationCompleted(object arg) {
            if ((this.DeletePhoneBookCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeletePhoneBookCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tandberg.com/TMS/PhoneBookService/1.0/MovePhoneBook", RequestNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", ResponseNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void MovePhoneBook(int PhoneBookId, int ParentPhoneBookId) {
            this.Invoke("MovePhoneBook", new object[] {
                        PhoneBookId,
                        ParentPhoneBookId});
        }
        
        /// <remarks/>
        public void MovePhoneBookAsync(int PhoneBookId, int ParentPhoneBookId) {
            this.MovePhoneBookAsync(PhoneBookId, ParentPhoneBookId, null);
        }
        
        /// <remarks/>
        public void MovePhoneBookAsync(int PhoneBookId, int ParentPhoneBookId, object userState) {
            if ((this.MovePhoneBookOperationCompleted == null)) {
                this.MovePhoneBookOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMovePhoneBookOperationCompleted);
            }
            this.InvokeAsync("MovePhoneBook", new object[] {
                        PhoneBookId,
                        ParentPhoneBookId}, this.MovePhoneBookOperationCompleted, userState);
        }
        
        private void OnMovePhoneBookOperationCompleted(object arg) {
            if ((this.MovePhoneBookCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MovePhoneBookCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tandberg.com/TMS/PhoneBookService/1.0/BindSourceToPhoneBook", RequestNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", ResponseNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void BindSourceToPhoneBook(int PhoneBookId, int PhoneBookSourceId, SyncDirection SyncDirection) {
            this.Invoke("BindSourceToPhoneBook", new object[] {
                        PhoneBookId,
                        PhoneBookSourceId,
                        SyncDirection});
        }
        
        /// <remarks/>
        public void BindSourceToPhoneBookAsync(int PhoneBookId, int PhoneBookSourceId, SyncDirection SyncDirection) {
            this.BindSourceToPhoneBookAsync(PhoneBookId, PhoneBookSourceId, SyncDirection, null);
        }
        
        /// <remarks/>
        public void BindSourceToPhoneBookAsync(int PhoneBookId, int PhoneBookSourceId, SyncDirection SyncDirection, object userState) {
            if ((this.BindSourceToPhoneBookOperationCompleted == null)) {
                this.BindSourceToPhoneBookOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBindSourceToPhoneBookOperationCompleted);
            }
            this.InvokeAsync("BindSourceToPhoneBook", new object[] {
                        PhoneBookId,
                        PhoneBookSourceId,
                        SyncDirection}, this.BindSourceToPhoneBookOperationCompleted, userState);
        }
        
        private void OnBindSourceToPhoneBookOperationCompleted(object arg) {
            if ((this.BindSourceToPhoneBookCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BindSourceToPhoneBookCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tandberg.com/TMS/PhoneBookService/1.0/UnbindSourceFromPhoneBook", RequestNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", ResponseNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UnbindSourceFromPhoneBook(int PhoneBookId, int PhoneBookSourceId) {
            this.Invoke("UnbindSourceFromPhoneBook", new object[] {
                        PhoneBookId,
                        PhoneBookSourceId});
        }
        
        /// <remarks/>
        public void UnbindSourceFromPhoneBookAsync(int PhoneBookId, int PhoneBookSourceId) {
            this.UnbindSourceFromPhoneBookAsync(PhoneBookId, PhoneBookSourceId, null);
        }
        
        /// <remarks/>
        public void UnbindSourceFromPhoneBookAsync(int PhoneBookId, int PhoneBookSourceId, object userState) {
            if ((this.UnbindSourceFromPhoneBookOperationCompleted == null)) {
                this.UnbindSourceFromPhoneBookOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUnbindSourceFromPhoneBookOperationCompleted);
            }
            this.InvokeAsync("UnbindSourceFromPhoneBook", new object[] {
                        PhoneBookId,
                        PhoneBookSourceId}, this.UnbindSourceFromPhoneBookOperationCompleted, userState);
        }
        
        private void OnUnbindSourceFromPhoneBookOperationCompleted(object arg) {
            if ((this.UnbindSourceFromPhoneBookCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UnbindSourceFromPhoneBookCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tandberg.com/TMS/PhoneBookService/1.0/GetSources", RequestNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", ResponseNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PhoneBookSource[] GetSources() {
            object[] results = this.Invoke("GetSources", new object[0]);
            return ((PhoneBookSource[])(results[0]));
        }
        
        /// <remarks/>
        public void GetSourcesAsync() {
            this.GetSourcesAsync(null);
        }
        
        /// <remarks/>
        public void GetSourcesAsync(object userState) {
            if ((this.GetSourcesOperationCompleted == null)) {
                this.GetSourcesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSourcesOperationCompleted);
            }
            this.InvokeAsync("GetSources", new object[0], this.GetSourcesOperationCompleted, userState);
        }
        
        private void OnGetSourcesOperationCompleted(object arg) {
            if ((this.GetSourcesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSourcesCompleted(this, new GetSourcesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tandberg.com/TMS/PhoneBookService/1.0/GetSourceParameters", RequestNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", ResponseNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PhoneBookSourceSettings GetSourceParameters(int SourceId) {
            object[] results = this.Invoke("GetSourceParameters", new object[] {
                        SourceId});
            return ((PhoneBookSourceSettings)(results[0]));
        }
        
        /// <remarks/>
        public void GetSourceParametersAsync(int SourceId) {
            this.GetSourceParametersAsync(SourceId, null);
        }
        
        /// <remarks/>
        public void GetSourceParametersAsync(int SourceId, object userState) {
            if ((this.GetSourceParametersOperationCompleted == null)) {
                this.GetSourceParametersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSourceParametersOperationCompleted);
            }
            this.InvokeAsync("GetSourceParameters", new object[] {
                        SourceId}, this.GetSourceParametersOperationCompleted, userState);
        }
        
        private void OnGetSourceParametersOperationCompleted(object arg) {
            if ((this.GetSourceParametersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSourceParametersCompleted(this, new GetSourceParametersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tandberg.com/TMS/PhoneBookService/1.0/DeleteSource", RequestNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", ResponseNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteSource(int SourceId) {
            this.Invoke("DeleteSource", new object[] {
                        SourceId});
        }
        
        /// <remarks/>
        public void DeleteSourceAsync(int SourceId) {
            this.DeleteSourceAsync(SourceId, null);
        }
        
        /// <remarks/>
        public void DeleteSourceAsync(int SourceId, object userState) {
            if ((this.DeleteSourceOperationCompleted == null)) {
                this.DeleteSourceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteSourceOperationCompleted);
            }
            this.InvokeAsync("DeleteSource", new object[] {
                        SourceId}, this.DeleteSourceOperationCompleted, userState);
        }
        
        private void OnDeleteSourceOperationCompleted(object arg) {
            if ((this.DeleteSourceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteSourceCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tandberg.com/TMS/PhoneBookService/1.0/CreateSource", RequestNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", ResponseNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PhoneBookSource CreateSource(PhoneBookSource Source, PhoneBookSourceSettings Settings) {
            object[] results = this.Invoke("CreateSource", new object[] {
                        Source,
                        Settings});
            return ((PhoneBookSource)(results[0]));
        }
        
        /// <remarks/>
        public void CreateSourceAsync(PhoneBookSource Source, PhoneBookSourceSettings Settings) {
            this.CreateSourceAsync(Source, Settings, null);
        }
        
        /// <remarks/>
        public void CreateSourceAsync(PhoneBookSource Source, PhoneBookSourceSettings Settings, object userState) {
            if ((this.CreateSourceOperationCompleted == null)) {
                this.CreateSourceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateSourceOperationCompleted);
            }
            this.InvokeAsync("CreateSource", new object[] {
                        Source,
                        Settings}, this.CreateSourceOperationCompleted, userState);
        }
        
        private void OnCreateSourceOperationCompleted(object arg) {
            if ((this.CreateSourceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateSourceCompleted(this, new CreateSourceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tandberg.com/TMS/PhoneBookService/1.0/UpdateSource", RequestNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", ResponseNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateSource(PhoneBookSource Source, PhoneBookSourceSettings Settings) {
            this.Invoke("UpdateSource", new object[] {
                        Source,
                        Settings});
        }
        
        /// <remarks/>
        public void UpdateSourceAsync(PhoneBookSource Source, PhoneBookSourceSettings Settings) {
            this.UpdateSourceAsync(Source, Settings, null);
        }
        
        /// <remarks/>
        public void UpdateSourceAsync(PhoneBookSource Source, PhoneBookSourceSettings Settings, object userState) {
            if ((this.UpdateSourceOperationCompleted == null)) {
                this.UpdateSourceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateSourceOperationCompleted);
            }
            this.InvokeAsync("UpdateSource", new object[] {
                        Source,
                        Settings}, this.UpdateSourceOperationCompleted, userState);
        }
        
        private void OnUpdateSourceOperationCompleted(object arg) {
            if ((this.UpdateSourceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateSourceCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tandberg.com/TMS/PhoneBookService/1.0/RenameSource", RequestNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", ResponseNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RenameSource(int SourceId, string Name) {
            this.Invoke("RenameSource", new object[] {
                        SourceId,
                        Name});
        }
        
        /// <remarks/>
        public void RenameSourceAsync(int SourceId, string Name) {
            this.RenameSourceAsync(SourceId, Name, null);
        }
        
        /// <remarks/>
        public void RenameSourceAsync(int SourceId, string Name, object userState) {
            if ((this.RenameSourceOperationCompleted == null)) {
                this.RenameSourceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRenameSourceOperationCompleted);
            }
            this.InvokeAsync("RenameSource", new object[] {
                        SourceId,
                        Name}, this.RenameSourceOperationCompleted, userState);
        }
        
        private void OnRenameSourceOperationCompleted(object arg) {
            if ((this.RenameSourceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RenameSourceCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tandberg.com/TMS/PhoneBookService/1.0/SearchPhoneBookSource", RequestNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", ResponseNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PhoneBookContact[] SearchPhoneBookSource(int SourceId, string SearchString, int maxResults) {
            object[] results = this.Invoke("SearchPhoneBookSource", new object[] {
                        SourceId,
                        SearchString,
                        maxResults});
            return ((PhoneBookContact[])(results[0]));
        }
        
        /// <remarks/>
        public void SearchPhoneBookSourceAsync(int SourceId, string SearchString, int maxResults) {
            this.SearchPhoneBookSourceAsync(SourceId, SearchString, maxResults, null);
        }
        
        /// <remarks/>
        public void SearchPhoneBookSourceAsync(int SourceId, string SearchString, int maxResults, object userState) {
            if ((this.SearchPhoneBookSourceOperationCompleted == null)) {
                this.SearchPhoneBookSourceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchPhoneBookSourceOperationCompleted);
            }
            this.InvokeAsync("SearchPhoneBookSource", new object[] {
                        SourceId,
                        SearchString,
                        maxResults}, this.SearchPhoneBookSourceOperationCompleted, userState);
        }
        
        private void OnSearchPhoneBookSourceOperationCompleted(object arg) {
            if ((this.SearchPhoneBookSourceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchPhoneBookSourceCompleted(this, new SearchPhoneBookSourceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tandberg.com/TMS/PhoneBookService/1.0/GetPhoneBookSourceContacts", RequestNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", ResponseNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PhoneBookContact[] GetPhoneBookSourceContacts(int SourceId, int MaxResults, int Offset) {
            object[] results = this.Invoke("GetPhoneBookSourceContacts", new object[] {
                        SourceId,
                        MaxResults,
                        Offset});
            return ((PhoneBookContact[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPhoneBookSourceContactsAsync(int SourceId, int MaxResults, int Offset) {
            this.GetPhoneBookSourceContactsAsync(SourceId, MaxResults, Offset, null);
        }
        
        /// <remarks/>
        public void GetPhoneBookSourceContactsAsync(int SourceId, int MaxResults, int Offset, object userState) {
            if ((this.GetPhoneBookSourceContactsOperationCompleted == null)) {
                this.GetPhoneBookSourceContactsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPhoneBookSourceContactsOperationCompleted);
            }
            this.InvokeAsync("GetPhoneBookSourceContacts", new object[] {
                        SourceId,
                        MaxResults,
                        Offset}, this.GetPhoneBookSourceContactsOperationCompleted, userState);
        }
        
        private void OnGetPhoneBookSourceContactsOperationCompleted(object arg) {
            if ((this.GetPhoneBookSourceContactsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPhoneBookSourceContactsCompleted(this, new GetPhoneBookSourceContactsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tandberg.com/TMS/PhoneBookService/1.0/CreateContact", RequestNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", ResponseNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PhoneBookContact CreateContact(int SourceId, string Name) {
            object[] results = this.Invoke("CreateContact", new object[] {
                        SourceId,
                        Name});
            return ((PhoneBookContact)(results[0]));
        }
        
        /// <remarks/>
        public void CreateContactAsync(int SourceId, string Name) {
            this.CreateContactAsync(SourceId, Name, null);
        }
        
        /// <remarks/>
        public void CreateContactAsync(int SourceId, string Name, object userState) {
            if ((this.CreateContactOperationCompleted == null)) {
                this.CreateContactOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateContactOperationCompleted);
            }
            this.InvokeAsync("CreateContact", new object[] {
                        SourceId,
                        Name}, this.CreateContactOperationCompleted, userState);
        }
        
        private void OnCreateContactOperationCompleted(object arg) {
            if ((this.CreateContactCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateContactCompleted(this, new CreateContactCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tandberg.com/TMS/PhoneBookService/1.0/RenameContact", RequestNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", ResponseNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RenameContact(int ContactId, string Name) {
            this.Invoke("RenameContact", new object[] {
                        ContactId,
                        Name});
        }
        
        /// <remarks/>
        public void RenameContactAsync(int ContactId, string Name) {
            this.RenameContactAsync(ContactId, Name, null);
        }
        
        /// <remarks/>
        public void RenameContactAsync(int ContactId, string Name, object userState) {
            if ((this.RenameContactOperationCompleted == null)) {
                this.RenameContactOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRenameContactOperationCompleted);
            }
            this.InvokeAsync("RenameContact", new object[] {
                        ContactId,
                        Name}, this.RenameContactOperationCompleted, userState);
        }
        
        private void OnRenameContactOperationCompleted(object arg) {
            if ((this.RenameContactCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RenameContactCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tandberg.com/TMS/PhoneBookService/1.0/DeleteContact", RequestNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", ResponseNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteContact(int ContactId) {
            this.Invoke("DeleteContact", new object[] {
                        ContactId});
        }
        
        /// <remarks/>
        public void DeleteContactAsync(int ContactId) {
            this.DeleteContactAsync(ContactId, null);
        }
        
        /// <remarks/>
        public void DeleteContactAsync(int ContactId, object userState) {
            if ((this.DeleteContactOperationCompleted == null)) {
                this.DeleteContactOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteContactOperationCompleted);
            }
            this.InvokeAsync("DeleteContact", new object[] {
                        ContactId}, this.DeleteContactOperationCompleted, userState);
        }
        
        private void OnDeleteContactOperationCompleted(object arg) {
            if ((this.DeleteContactCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteContactCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tandberg.com/TMS/PhoneBookService/1.0/CreateContactMethod", RequestNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", ResponseNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PhoneBookContactMethod CreateContactMethod(int SourceId, int ContactId, PhoneBookContactMethodType ContactMethodType, string DialString1, string DialString2, string DialString3, string DialString4, string Description, int Bandwidth) {
            object[] results = this.Invoke("CreateContactMethod", new object[] {
                        SourceId,
                        ContactId,
                        ContactMethodType,
                        DialString1,
                        DialString2,
                        DialString3,
                        DialString4,
                        Description,
                        Bandwidth});
            return ((PhoneBookContactMethod)(results[0]));
        }
        
        /// <remarks/>
        public void CreateContactMethodAsync(int SourceId, int ContactId, PhoneBookContactMethodType ContactMethodType, string DialString1, string DialString2, string DialString3, string DialString4, string Description, int Bandwidth) {
            this.CreateContactMethodAsync(SourceId, ContactId, ContactMethodType, DialString1, DialString2, DialString3, DialString4, Description, Bandwidth, null);
        }
        
        /// <remarks/>
        public void CreateContactMethodAsync(int SourceId, int ContactId, PhoneBookContactMethodType ContactMethodType, string DialString1, string DialString2, string DialString3, string DialString4, string Description, int Bandwidth, object userState) {
            if ((this.CreateContactMethodOperationCompleted == null)) {
                this.CreateContactMethodOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateContactMethodOperationCompleted);
            }
            this.InvokeAsync("CreateContactMethod", new object[] {
                        SourceId,
                        ContactId,
                        ContactMethodType,
                        DialString1,
                        DialString2,
                        DialString3,
                        DialString4,
                        Description,
                        Bandwidth}, this.CreateContactMethodOperationCompleted, userState);
        }
        
        private void OnCreateContactMethodOperationCompleted(object arg) {
            if ((this.CreateContactMethodCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateContactMethodCompleted(this, new CreateContactMethodCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tandberg.com/TMS/PhoneBookService/1.0/DeleteContactMethod", RequestNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", ResponseNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteContactMethod(int ContactId, int ContactMethodId) {
            this.Invoke("DeleteContactMethod", new object[] {
                        ContactId,
                        ContactMethodId});
        }
        
        /// <remarks/>
        public void DeleteContactMethodAsync(int ContactId, int ContactMethodId) {
            this.DeleteContactMethodAsync(ContactId, ContactMethodId, null);
        }
        
        /// <remarks/>
        public void DeleteContactMethodAsync(int ContactId, int ContactMethodId, object userState) {
            if ((this.DeleteContactMethodOperationCompleted == null)) {
                this.DeleteContactMethodOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteContactMethodOperationCompleted);
            }
            this.InvokeAsync("DeleteContactMethod", new object[] {
                        ContactId,
                        ContactMethodId}, this.DeleteContactMethodOperationCompleted, userState);
        }
        
        private void OnDeleteContactMethodOperationCompleted(object arg) {
            if ((this.DeleteContactMethodCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteContactMethodCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tandberg.com/TMS/PhoneBookService/1.0/AddPhoneBookToSystem", RequestNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", ResponseNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddPhoneBookToSystem(SystemId systemId, PhoneBookId phoneBookId) {
            this.Invoke("AddPhoneBookToSystem", new object[] {
                        systemId,
                        phoneBookId});
        }
        
        /// <remarks/>
        public void AddPhoneBookToSystemAsync(SystemId systemId, PhoneBookId phoneBookId) {
            this.AddPhoneBookToSystemAsync(systemId, phoneBookId, null);
        }
        
        /// <remarks/>
        public void AddPhoneBookToSystemAsync(SystemId systemId, PhoneBookId phoneBookId, object userState) {
            if ((this.AddPhoneBookToSystemOperationCompleted == null)) {
                this.AddPhoneBookToSystemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddPhoneBookToSystemOperationCompleted);
            }
            this.InvokeAsync("AddPhoneBookToSystem", new object[] {
                        systemId,
                        phoneBookId}, this.AddPhoneBookToSystemOperationCompleted, userState);
        }
        
        private void OnAddPhoneBookToSystemOperationCompleted(object arg) {
            if ((this.AddPhoneBookToSystemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddPhoneBookToSystemCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tandberg.com/TMS/PhoneBookService/1.0/AddSystemsToPhoneBook", RequestNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", ResponseNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddSystemsToPhoneBook(PhoneBookId phoneBookId, SystemId[] systemIds) {
            this.Invoke("AddSystemsToPhoneBook", new object[] {
                        phoneBookId,
                        systemIds});
        }
        
        /// <remarks/>
        public void AddSystemsToPhoneBookAsync(PhoneBookId phoneBookId, SystemId[] systemIds) {
            this.AddSystemsToPhoneBookAsync(phoneBookId, systemIds, null);
        }
        
        /// <remarks/>
        public void AddSystemsToPhoneBookAsync(PhoneBookId phoneBookId, SystemId[] systemIds, object userState) {
            if ((this.AddSystemsToPhoneBookOperationCompleted == null)) {
                this.AddSystemsToPhoneBookOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddSystemsToPhoneBookOperationCompleted);
            }
            this.InvokeAsync("AddSystemsToPhoneBook", new object[] {
                        phoneBookId,
                        systemIds}, this.AddSystemsToPhoneBookOperationCompleted, userState);
        }
        
        private void OnAddSystemsToPhoneBookOperationCompleted(object arg) {
            if ((this.AddSystemsToPhoneBookCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddSystemsToPhoneBookCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tandberg.com/TMS/PhoneBookService/1.0/RemovePhoneBooksFromSystem", RequestNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", ResponseNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RemovePhoneBooksFromSystem(SystemId id) {
            this.Invoke("RemovePhoneBooksFromSystem", new object[] {
                        id});
        }
        
        /// <remarks/>
        public void RemovePhoneBooksFromSystemAsync(SystemId id) {
            this.RemovePhoneBooksFromSystemAsync(id, null);
        }
        
        /// <remarks/>
        public void RemovePhoneBooksFromSystemAsync(SystemId id, object userState) {
            if ((this.RemovePhoneBooksFromSystemOperationCompleted == null)) {
                this.RemovePhoneBooksFromSystemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemovePhoneBooksFromSystemOperationCompleted);
            }
            this.InvokeAsync("RemovePhoneBooksFromSystem", new object[] {
                        id}, this.RemovePhoneBooksFromSystemOperationCompleted, userState);
        }
        
        private void OnRemovePhoneBooksFromSystemOperationCompleted(object arg) {
            if ((this.RemovePhoneBooksFromSystemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemovePhoneBooksFromSystemCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tandberg.com/TMS/PhoneBookService/1.0/RemoveSystemsFromPhoneBook", RequestNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", ResponseNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RemoveSystemsFromPhoneBook(PhoneBookId phoneBookId, SystemId[] systemIds) {
            this.Invoke("RemoveSystemsFromPhoneBook", new object[] {
                        phoneBookId,
                        systemIds});
        }
        
        /// <remarks/>
        public void RemoveSystemsFromPhoneBookAsync(PhoneBookId phoneBookId, SystemId[] systemIds) {
            this.RemoveSystemsFromPhoneBookAsync(phoneBookId, systemIds, null);
        }
        
        /// <remarks/>
        public void RemoveSystemsFromPhoneBookAsync(PhoneBookId phoneBookId, SystemId[] systemIds, object userState) {
            if ((this.RemoveSystemsFromPhoneBookOperationCompleted == null)) {
                this.RemoveSystemsFromPhoneBookOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveSystemsFromPhoneBookOperationCompleted);
            }
            this.InvokeAsync("RemoveSystemsFromPhoneBook", new object[] {
                        phoneBookId,
                        systemIds}, this.RemoveSystemsFromPhoneBookOperationCompleted, userState);
        }
        
        private void OnRemoveSystemsFromPhoneBookOperationCompleted(object arg) {
            if ((this.RemoveSystemsFromPhoneBookCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveSystemsFromPhoneBookCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tandberg.com/TMS/PhoneBookService/1.0/GetPhoneBooksForSystem", RequestNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", ResponseNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PhoneBookId[] GetPhoneBooksForSystem(SystemId systemId) {
            object[] results = this.Invoke("GetPhoneBooksForSystem", new object[] {
                        systemId});
            return ((PhoneBookId[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPhoneBooksForSystemAsync(SystemId systemId) {
            this.GetPhoneBooksForSystemAsync(systemId, null);
        }
        
        /// <remarks/>
        public void GetPhoneBooksForSystemAsync(SystemId systemId, object userState) {
            if ((this.GetPhoneBooksForSystemOperationCompleted == null)) {
                this.GetPhoneBooksForSystemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPhoneBooksForSystemOperationCompleted);
            }
            this.InvokeAsync("GetPhoneBooksForSystem", new object[] {
                        systemId}, this.GetPhoneBooksForSystemOperationCompleted, userState);
        }
        
        private void OnGetPhoneBooksForSystemOperationCompleted(object arg) {
            if ((this.GetPhoneBooksForSystemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPhoneBooksForSystemCompleted(this, new GetPhoneBooksForSystemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tandberg.com/TMS/PhoneBookService/1.0/GetTmsServerInfo", RequestNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", ResponseNamespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TmsServerInfo GetTmsServerInfo() {
            object[] results = this.Invoke("GetTmsServerInfo", new object[0]);
            return ((TmsServerInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetTmsServerInfoAsync() {
            this.GetTmsServerInfoAsync(null);
        }
        
        /// <remarks/>
        public void GetTmsServerInfoAsync(object userState) {
            if ((this.GetTmsServerInfoOperationCompleted == null)) {
                this.GetTmsServerInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTmsServerInfoOperationCompleted);
            }
            this.InvokeAsync("GetTmsServerInfo", new object[0], this.GetTmsServerInfoOperationCompleted, userState);
        }
        
        private void OnGetTmsServerInfoOperationCompleted(object arg) {
            if ((this.GetTmsServerInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTmsServerInfoCompleted(this, new GetTmsServerInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/")]
    public partial class PhoneBook {
        
        private int idField;
        
        private string nameField;
        
        private int parentIdField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int ParentId {
            get {
                return this.parentIdField;
            }
            set {
                this.parentIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/")]
    public partial class TmsServerInfo {
        
        private string databaseHostField;
        
        private string databaseInstanceField;
        
        /// <remarks/>
        public string DatabaseHost {
            get {
                return this.databaseHostField;
            }
            set {
                this.databaseHostField = value;
            }
        }
        
        /// <remarks/>
        public string DatabaseInstance {
            get {
                return this.databaseInstanceField;
            }
            set {
                this.databaseInstanceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PhoneBookId))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/")]
    public abstract partial class TMSIntId {
        
        private int idField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/")]
    public partial class PhoneBookId : TMSIntId {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SystemId))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/")]
    public abstract partial class TMSLongId {
        
        private long idField;
        
        /// <remarks/>
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/")]
    public partial class SystemId : TMSLongId {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/")]
    public partial class PhoneBookContactMethod {
        
        private int idField;
        
        private PhoneBookContactMethodType typeField;
        
        private string displayStringField;
        
        private string fQDialStringField;
        
        private string descriptionField;
        
        private int bandwidthField;
        
        private bool isRestrictedISDNField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public PhoneBookContactMethodType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayString {
            get {
                return this.displayStringField;
            }
            set {
                this.displayStringField = value;
            }
        }
        
        /// <remarks/>
        public string FQDialString {
            get {
                return this.fQDialStringField;
            }
            set {
                this.fQDialStringField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public int Bandwidth {
            get {
                return this.bandwidthField;
            }
            set {
                this.bandwidthField = value;
            }
        }
        
        /// <remarks/>
        public bool IsRestrictedISDN {
            get {
                return this.isRestrictedISDNField;
            }
            set {
                this.isRestrictedISDNField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/")]
    public enum PhoneBookContactMethodType {
        
        /// <remarks/>
        Unknown,
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        TMSSys,
        
        /// <remarks/>
        IP,
        
        /// <remarks/>
        ISDN,
        
        /// <remarks/>
        ISDN2,
        
        /// <remarks/>
        Voice,
        
        /// <remarks/>
        H323,
        
        /// <remarks/>
        SIP,
        
        /// <remarks/>
        Tel3G,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/")]
    public partial class PhoneBookContact {
        
        private int idField;
        
        private string nameField;
        
        private PhoneBookContactMethod[] contactMethodsField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public PhoneBookContactMethod[] ContactMethods {
            get {
                return this.contactMethodsField;
            }
            set {
                this.contactMethodsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/")]
    public partial class PhoneBookSourceSetting {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/")]
    public partial class PhoneBookSourceSettings {
        
        private PhoneBookSourceSetting[] settingsField;
        
        /// <remarks/>
        public PhoneBookSourceSetting[] Settings {
            get {
                return this.settingsField;
            }
            set {
                this.settingsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/")]
    public partial class PhoneBookSource {
        
        private int idField;
        
        private string nameField;
        
        private PhoneBookSourceType typeField;
        
        private bool isConnectedField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public PhoneBookSourceType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public bool IsConnected {
            get {
                return this.isConnectedField;
            }
            set {
                this.isConnectedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/")]
    public enum PhoneBookSourceType {
        
        /// <remarks/>
        Unknown,
        
        /// <remarks/>
        TMS,
        
        /// <remarks/>
        TMSEndPoints,
        
        /// <remarks/>
        PolycomGMS,
        
        /// <remarks/>
        Gatekeeper,
        
        /// <remarks/>
        SystemLocalPhoneBook,
        
        /// <remarks/>
        OtherTMSPhoneBook,
        
        /// <remarks/>
        H350,
        
        /// <remarks/>
        ActiveDirectory,
        
        /// <remarks/>
        H350ByUser,
        
        /// <remarks/>
        HTTPPhoneBook,
        
        /// <remarks/>
        TMSUserPhoneBook,
        
        /// <remarks/>
        MoviVideoServer,
        
        /// <remarks/>
        ProvisioningServer,
        
        /// <remarks/>
        ManualList,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/")]
    public partial class PhoneBookToSourceBinding {
        
        private int phoneBookIdField;
        
        private int phoneBookSourceIdField;
        
        private SyncDirection syncDirectionField;
        
        private BindingStatus statusField;
        
        /// <remarks/>
        public int PhoneBookId {
            get {
                return this.phoneBookIdField;
            }
            set {
                this.phoneBookIdField = value;
            }
        }
        
        /// <remarks/>
        public int PhoneBookSourceId {
            get {
                return this.phoneBookSourceIdField;
            }
            set {
                this.phoneBookSourceIdField = value;
            }
        }
        
        /// <remarks/>
        public SyncDirection SyncDirection {
            get {
                return this.syncDirectionField;
            }
            set {
                this.syncDirectionField = value;
            }
        }
        
        /// <remarks/>
        public BindingStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/")]
    public enum SyncDirection {
        
        /// <remarks/>
        Unknown,
        
        /// <remarks/>
        ImportToTMS,
        
        /// <remarks/>
        ImportToTMSAndExportToExternalSource,
        
        /// <remarks/>
        SearchOnly,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tandberg.com/TMS/PhoneBookService/1.0/")]
    public enum BindingStatus {
        
        /// <remarks/>
        Unknown,
        
        /// <remarks/>
        Connected,
        
        /// <remarks/>
        Connecting,
        
        /// <remarks/>
        Disconnecting,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void PingCompletedEventHandler(object sender, PingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetPhoneBooksCompletedEventHandler(object sender, GetPhoneBooksCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPhoneBooksCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPhoneBooksCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PhoneBook[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PhoneBook[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetSourcesForPhoneBookCompletedEventHandler(object sender, GetSourcesForPhoneBookCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSourcesForPhoneBookCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSourcesForPhoneBookCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PhoneBookToSourceBinding[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PhoneBookToSourceBinding[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void CreatePhoneBookCompletedEventHandler(object sender, CreatePhoneBookCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreatePhoneBookCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreatePhoneBookCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PhoneBook Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PhoneBook)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void RenamePhoneBookCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void DeletePhoneBookCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void MovePhoneBookCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void BindSourceToPhoneBookCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void UnbindSourceFromPhoneBookCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetSourcesCompletedEventHandler(object sender, GetSourcesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSourcesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSourcesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PhoneBookSource[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PhoneBookSource[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetSourceParametersCompletedEventHandler(object sender, GetSourceParametersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSourceParametersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSourceParametersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PhoneBookSourceSettings Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PhoneBookSourceSettings)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void DeleteSourceCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void CreateSourceCompletedEventHandler(object sender, CreateSourceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateSourceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateSourceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PhoneBookSource Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PhoneBookSource)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void UpdateSourceCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void RenameSourceCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void SearchPhoneBookSourceCompletedEventHandler(object sender, SearchPhoneBookSourceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchPhoneBookSourceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchPhoneBookSourceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PhoneBookContact[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PhoneBookContact[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetPhoneBookSourceContactsCompletedEventHandler(object sender, GetPhoneBookSourceContactsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPhoneBookSourceContactsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPhoneBookSourceContactsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PhoneBookContact[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PhoneBookContact[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void CreateContactCompletedEventHandler(object sender, CreateContactCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateContactCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateContactCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PhoneBookContact Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PhoneBookContact)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void RenameContactCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void DeleteContactCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void CreateContactMethodCompletedEventHandler(object sender, CreateContactMethodCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateContactMethodCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateContactMethodCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PhoneBookContactMethod Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PhoneBookContactMethod)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void DeleteContactMethodCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void AddPhoneBookToSystemCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void AddSystemsToPhoneBookCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void RemovePhoneBooksFromSystemCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void RemoveSystemsFromPhoneBookCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetPhoneBooksForSystemCompletedEventHandler(object sender, GetPhoneBooksForSystemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPhoneBooksForSystemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPhoneBooksForSystemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PhoneBookId[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PhoneBookId[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetTmsServerInfoCompletedEventHandler(object sender, GetTmsServerInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTmsServerInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTmsServerInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TmsServerInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TmsServerInfo)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591