using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Text;
using KeytiaServiceBL;

namespace KeytiaWeb.UserInterface.DashboardFC.Reportes
{
    public class ConsultasSYO
    {
        public string ConsultaPruebaSeeYouOn(int iCodUsuario)
        {
            StringBuilder lsb = new StringBuilder();
            lsb.Append("declare @iCodCatalogo INT\r ");
            lsb.Append("declare @iCodClient INT \r ");
            lsb.Append("select @iCodCatalogo = iCodCatalogo \nfrom K5SeeYouOn.[VisHistoricos('Client','Clientes','Español')] \nwhere ");
            lsb.Append("\tvchDescripcion='Evox' \nand dtinivigencia<>dtfinvigencia \nand dtfinvigencia>=getdate()\r ");
            //lsb.Append("select   @iCodClient=Client from K5SeeYouOn.[VisHistoricos('Usuar','Usuarios','Español')] where iCodCatalogo=" + iCodUsuario + " and dtinivigencia<>dtfinvigencia and dtfinvigencia>=getdate()\r ");
            lsb.Append("select @iCodClient=Empre.Client from K5SeeYouOn.[vishistoricos('usuar','usuarios','español')] Usuar\r");
            lsb.Append("join K5SeeYouOn.[vishistoricos('Emple','Empleados','español')] Emple\r");
            lsb.Append("on Emple.dtinivigencia<>Emple.dtfinvigencia\r");
            lsb.Append("and Emple.dtfinvigencia>=getdate()\r");
            lsb.Append("and Emple.Usuar = Usuar.icodCatalogo");
            lsb.Append("join K5SeeYouOn.[vishistoricos('Empre','Empresas','español')] Empre\r");
            lsb.Append("on Empre.dtinivigencia<>Empre.dtfinvigencia\r");
            lsb.Append("and Empre.dtfinvigencia>=getdate()\r");
            lsb.Append("and Usuar.Empre = Empre.icodCatalogo\r");
            lsb.Append("where usuar.dtinivigencia<>usuar.dtfinvigencia\r");
            lsb.Append("and usuar.dtfinvigencia>=getdate()\r");
            lsb.Append("and usuar.icodcatalogo = " + iCodUsuario + "\r");
            lsb.Append("if(@iCodCatalogo=@iCodClient)\r ");
            lsb.Append("Begin\r ");
            lsb.Append("DECLARE @auxCliente VARCHAR(MAX) = '200071'\r ");
            lsb.Append("SELECT \r ");
            lsb.Append("TOP(10) \r ");
            lsb.Append("DET.SYOSourceNumber,\r ");
            lsb.Append("SUM(SYODurationSec) AS Total\r ");
            lsb.Append("FROM\r ");
            lsb.Append("K5SeeYouOn.[VisDetallados('Detall','DetalleCDRSeeYouOn','Español')] DET\r ");
            lsb.Append("JOIN K5SeeYouOn.[vishistoricos('SYOUri','SYO Uris','Español')] URI\r ");
            lsb.Append("ON DET.SYOUriDesc = URI.vchDescripcion\r ");
            lsb.Append("AND URI.dtinivigencia <> URI.dtfinvigencia\r");
            lsb.Append("AND URI.dtfinvigencia >= getdate()\r ");
            lsb.Append("AND URI.CLIENT = @auxCliente\r ");
            lsb.Append("GROUP BY DET.SYOSourceNumber\r ");
            lsb.Append("ORDER BY Total DESC\r ");
            lsb.Append("End\r ");
            return lsb.ToString();
        }
        public string ConsultaUsuariosMasTraficoSYO(int iCodUsuario, string fechaInicio, string fechaFin)
        {
            StringBuilder lsb = new StringBuilder();
            lsb.Append("DECLARE @FEchaInicio DATETIME =  '2016-07-01' \r ");
            lsb.Append("DECLARE @FEchaFin DATETIME =  DATEADD (MONTH , 1, @FEchaInicio)  \r ");
            lsb.Append("SELECT \r ");
            lsb.Append("TOP(10) \r ");
            lsb.Append("iCodCatalogo=CONVERT(VARCHAR,URI.iCodCatalogo,120),\r ");
            lsb.Append("DET.SYOSourceNumber,\r ");
            lsb.Append("Emple.NomCompleto as SYODisplayName,\r ");
            lsb.Append("SUM(ceiling(convert(float,SYODurationSec)/60.00)) AS Total\r ");
            lsb.Append("FROM\r ");
            lsb.Append("K5SeeYouOn.[VisDetallados('Detall','DetalleCDRSeeYouOn','Español')] DET\r ");
            lsb.Append("JOIN K5SeeYouOn.[vishistoricos('SYOUri','SYO Uris','Español')] URI\r");
            lsb.Append("ON DET.SYOUriDesc = URI.vchDescripcion\r ");
            lsb.Append("JOIN  K5SeeYouOn.[VisHistoricos('Emple','Empleados','Español')] Emple\r");
            lsb.Append("ON Emple.icodcatalogo = Uri.Emple\r ");
            lsb.Append("AND URI.dtinivigencia <> URI.dtfinvigencia\r ");
            lsb.Append("AND URI.dtfinvigencia >= getdate()\r ");
            lsb.Append("AND SYOTime >='" + fechaInicio + "'");
            lsb.Append("AND SYOTime <= '" + fechaFin + "'");
            lsb.Append("GROUP BY URI.iCodCatalogo, DET.SYOSourceNumber, URI.SYODisplayName,Emple.NomCompleto\r ");
            lsb.Append("ORDER BY Total DESC\r ");
            return lsb.ToString();
        }
        public string ConsultaClientesConMasTraficoSYO(int iCodUsuario, string fechaInicio, string fechaFin)
        {
            StringBuilder lsb = new StringBuilder();
            lsb.Append("DECLARE @FechaInicio DATETIME = '2016-07-01 00:00:00.000'\r ");
            lsb.Append("DECLARE @FechaFin DATETIME = DATEADD (MONTH , 1, @FEchaInicio) \r ");
            lsb.Append("DECLARE @Top INT = 10 \r ");
            lsb.Append("IF(@Top != 0) \r");
            lsb.Append("BEGIN \r ");
            lsb.Append("SELECT TOP(@Top) * FROM(\r ");
            lsb.Append("SELECT UPPER(CLI.vchCodigo) AS Codigo, UPPER(CLI.vchDescripcion) AS Descripcion, SUM(ceiling(convert(float,CDR.SYODurationSec)/60.00)) AS Segundos FROM\r ");
            lsb.Append("K5SeeYouOn.[VisHistoricos('Client','Clientes','Español')] CLI\r ");
            lsb.Append("JOIN K5SeeYouOn.[vishistoricos('SYOUri','SYO Uris','Español')] URI\r ");
            lsb.Append("ON URI.Client = CLI.iCodCatalogo\r");
            lsb.Append("JOIN K5SeeYouOn.[VisDetallados('Detall','DetalleCDRSeeYouOn','Español')] CDR\r ");
            lsb.Append("ON CDR.SYOUri = URI.iCodCatalogo\r ");
            lsb.Append("AND CDR.SYOTime >='" + fechaInicio + "'");
            lsb.Append("AND CDR.SYOTime < = '" + fechaFin + "'");
            lsb.Append("AND URI.dtinivigencia <> URI.dtfinvigencia\r ");
            lsb.Append("AND URI.dtfinvigencia >= GETDATE()\r ");
            lsb.Append("AND CLI.dtinivigencia <> CLI.dtfinvigencia\r ");
            lsb.Append("AND	CLI.dtfinvigencia >= GETDATE()\r ");
            lsb.Append("AND CLI.iCodCatalogo NOT IN(200002,351)\r");
            lsb.Append("GROUP BY CLI.vchCodigo, CLI.vchDescripcion\r ");
            lsb.Append(") AS FINAL\r ");
            lsb.Append("ORDER BY Segundos DESC\r ");
            lsb.Append("END ELSE BEGIN PRINT ('ELSE') SELECT * FROM(");
            lsb.Append("SELECT UPPER(CLI.vchCodigo) AS Codigo, UPPER(CLI.vchDescripcion) AS Descripcion, SUM(ceiling(convert(float,CDR.SYODurationSec)/60.00)) AS Segundos FROM\r ");
            lsb.Append("K5SeeYouOn.[VisHistoricos('Client','Clientes','Español')] CLI\r");
            lsb.Append("JOIN K5SeeYouOn.[vishistoricos('SYOUri','SYO Uris','Español')] URI\r ");
            lsb.Append("ON URI.Client = CLI.iCodCatalogo\r");
            lsb.Append("JOIN K5SeeYouOn.[VisDetallados('Detall','DetalleCDRSeeYouOn','Español')] CDR\r ");
            lsb.Append("ON CDR.SYOUri = URI.iCodCatalogo\r");
            lsb.Append("AND CDR.SYOTime >= @FechaInicio\r");
            lsb.Append("AND CDR.SYOTime < @FechaFin\r ");
            lsb.Append("AND URI.dtinivigencia <> URI.dtfinvigencia\r");
            lsb.Append("AND URI.dtfinvigencia >= GETDATE()\r ");
            lsb.Append("AND CLI.dtinivigencia <> CLI.dtfinvigencia\r");
            lsb.Append("AND	CLI.dtfinvigencia >= GETDATE()\r ");
            lsb.Append("AND CLI.iCodCatalogo NOT IN(200002,351)\r");
            lsb.Append("GROUP BY CLI.vchCodigo, CLI.vchDescripcion\r ");
            lsb.Append(") AS FINAL\r");
            lsb.Append("ORDER BY Segundos DESC\r ");
            lsb.Append("END\r");
            return lsb.ToString();
        }
        public string ConsultaClientesConMenosTraficoSYO(int iCodUsuario, string fechaInicio, string fechaFin)
        {
            StringBuilder lsb = new StringBuilder();
            lsb.Append("DECLARE @FechaInicio DATETIME = '2016-07-01 00:00:00.000'\r ");
            lsb.Append("DECLARE @FechaFin DATETIME = DATEADD (MONTH , 1, @FEchaInicio) -- Fecha Fin -- '2016-07-30 09:26:57.000'\r ");
            lsb.Append("DECLARE @Top INT = 10\r ");
            lsb.Append("IF(@Top != 0) \r");
            lsb.Append("IF(@Top != 0) \r ");
            lsb.Append("BEGIN SELECT TOP(@Top) Descripcion, Segundos FROM(\r ");
            lsb.Append("SELECT UPPER(CLI.vchCodigo) AS Codigo, UPPER(CLI.vchDescripcion) AS Descripcion, SUM(ceiling(convert(float,CDR.SYODurationSec)/60.00)) AS Segundos FROM\r ");
            lsb.Append("K5SeeYouOn.[VisHistoricos('Client','Clientes','Español')] CLI\r ");
            lsb.Append("JOIN K5SeeYouOn.[vishistoricos('SYOUri','SYO Uris','Español')] URI\r ");
            lsb.Append("ON URI.Client = CLI.iCodCatalogo\r");
            lsb.Append("JOIN K5SeeYouOn.[VisDetallados('Detall','DetalleCDRSeeYouOn','Español')] CDR\r ");
            lsb.Append("ON CDR.SYOUri = URI.iCodCatalogo\r ");
            lsb.Append("AND CDR.SYOTime >='" + fechaInicio + "'");
            lsb.Append("AND CDR.SYOTime < = '" + fechaFin + "'");
            lsb.Append("AND URI.dtinivigencia <> URI.dtfinvigencia\r ");
            lsb.Append("AND URI.dtfinvigencia >= GETDATE()\r ");
            lsb.Append("AND CLI.dtinivigencia <> CLI.dtfinvigencia\r ");
            lsb.Append("AND	CLI.dtfinvigencia >= GETDATE()\r ");
            lsb.Append("AND CLI.iCodCatalogo NOT IN(200002,351)\r");
            lsb.Append("GROUP BY CLI.vchCodigo, CLI.vchDescripcion\r ");
            lsb.Append(") AS FINAL\r ");
            lsb.Append("ORDER BY Segundos ASC\r ");
            lsb.Append("END ELSE BEGIN PRINT ('ELSE') SELECT DESCRIPCION, SEGUNDOS FROM(");
            lsb.Append("SELECT UPPER(CLI.vchCodigo) AS Codigo, UPPER(CLI.vchDescripcion) AS Descripcion, SUM(ceiling(convert(float,CDR.SYODurationSec)/60.00)) AS Segundos FROM\r ");
            lsb.Append("K5SeeYouOn.[VisHistoricos('Client','Clientes','Español')] CLI\r");
            lsb.Append("JOIN K5SeeYouOn.[vishistoricos('SYOUri','SYO Uris','Español')] URI\r ");
            lsb.Append("ON URI.Client = CLI.iCodCatalogo\r");
            lsb.Append("JOIN K5SeeYouOn.[VisDetallados('Detall','DetalleCDRSeeYouOn','Español')] CDR\r ");
            lsb.Append("ON CDR.SYOUri = URI.iCodCatalogo\r");
            lsb.Append("AND CDR.SYOTime >= @FechaInicio\r");
            lsb.Append("AND CDR.SYOTime < @FechaFin\r ");
            lsb.Append("AND URI.dtinivigencia <> URI.dtfinvigencia\r");
            lsb.Append("AND URI.dtfinvigencia >= GETDATE()\r ");
            lsb.Append("AND CLI.dtinivigencia <> CLI.dtfinvigencia\r");
            lsb.Append("AND	CLI.dtfinvigencia >= GETDATE()\r ");
            lsb.Append("AND CLI.iCodCatalogo NOT IN(200002,351)\r");
            lsb.Append("GROUP BY CLI.vchCodigo, CLI.vchDescripcion\r ");
            lsb.Append(") AS FINAL\r");
            lsb.Append("ORDER BY Segundos ASC\r ");
            lsb.Append("END\r");
            return lsb.ToString();
        }

        public string ConsultaDestinosMasMarcadosSYO(int iCodUsuario, string fechaInicio, string fechaFin)
        {
            StringBuilder lsb = new StringBuilder();
            lsb.Append("DECLARE @Cliente VARCHAR(MAX) =(\r");
            lsb.Append("select Empre.Client from K5SeeYouOn.[vishistoricos('usuar','usuarios','español')] Usuar\r");
            lsb.Append("join K5SeeYouOn.[vishistoricos('Emple','Empleados','español')] Emple\r");
            lsb.Append("on Emple.dtinivigencia<>Emple.dtfinvigencia\r");
            lsb.Append("and Emple.dtfinvigencia>=getdate()\r");
            lsb.Append("and Emple.Usuar = Usuar.icodCatalogo\r");
            lsb.Append("join K5SeeYouOn.[vishistoricos('Empre','Empresas','español')] Empre\r");
            lsb.Append("on Empre.dtinivigencia<>Empre.dtfinvigencia\r");
            lsb.Append("and Empre.dtfinvigencia>=getdate()\r");
            lsb.Append("and Usuar.Empre = Empre.icodCatalogo\r");
            lsb.Append("where usuar.dtinivigencia<>usuar.dtfinvigencia\r");
            lsb.Append("and usuar.dtfinvigencia>=getdate()\r");
            lsb.Append("and usuar.icodcatalogo = " + iCodUsuario + "\r");
            lsb.Append(")\r");
            lsb.Append("DECLARE @FechaInicio DATETIME = '2016-07-01 00:00:00.000'\r ");
            lsb.Append("DECLARE @FechaFin DATETIME = DATEADD (MONTH , 1, @FEchaInicio)\r ");
            lsb.Append("DECLARE @Top INT = 10 \r");
            lsb.Append("SELECT *FROM(SELECT TOP(@Top) \r ");
            lsb.Append("CDR.SYODestinationNumber AS Marcados, COUNT(CDR.SYODestinationNumber) AS NoDeMarcaciones FROM\r ");
            lsb.Append("K5SeeYouOn.[VisHistoricos('Client','Clientes','Español')] CLI\r ");
            lsb.Append("JOIN K5SeeYouOn.[vishistoricos('SYOUri','SYO Uris','Español')] URI\r ");
            lsb.Append("ON URI.Client = CLI.iCodCatalogo\r ");
            lsb.Append("JOIN K5SeeYouOn.[VisDetallados('Detall','DetalleCDRSeeYouOn','Español')] CDR\r");
            lsb.Append("ON URI.iCodCatalogo = CDR.SYOUri\r ");
            lsb.Append("AND URI.dtinivigencia <> URI.dtfinvigencia\r ");
            lsb.Append("AND URI.dtfinvigencia >= GETDATE()\r ");
            lsb.Append("AND CLI.dtinivigencia <> CLI.dtfinvigencia\r ");
            lsb.Append("AND	CLI.dtfinvigencia >= GETDATE()\r ");
            lsb.Append("AND CDR.SYOTime >='" + fechaInicio + "'");
            lsb.Append("AND CDR.SYOTime < = '" + fechaFin + "'");
            lsb.Append("AND URI.Client = @Cliente GROUP BY CDR.SYODestinationNumber) AS Final ORDER BY NoDeMarcaciones DESC\r");
            return lsb.ToString();
        }
        public string ConsultaUsoDeInfraestructuraPorUriSYO(int iCodUsuario, string fechaInicio, string fechaFin)
        {
            StringBuilder lsb = new StringBuilder();
            lsb.Append("DECLARE @Cliente VARCHAR(MAX) =(\r");
            lsb.Append("select Empre.Client from K5SeeYouOn.[vishistoricos('usuar','usuarios','español')] Usuar\r");
            lsb.Append("join K5SeeYouOn.[vishistoricos('Emple','Empleados','español')] Emple\r");
            lsb.Append("on Emple.dtinivigencia<>Emple.dtfinvigencia\r");
            lsb.Append("and Emple.dtfinvigencia>=getdate()\r");
            lsb.Append("and Emple.Usuar = Usuar.icodCatalogo\r");
            lsb.Append("join K5SeeYouOn.[vishistoricos('Empre','Empresas','español')] Empre\r");
            lsb.Append("on Empre.dtinivigencia<>Empre.dtfinvigencia\r");
            lsb.Append("and Empre.dtfinvigencia>=getdate()\r");
            lsb.Append("and Usuar.Empre = Empre.icodCatalogo\r");
            lsb.Append("where usuar.dtinivigencia<>usuar.dtfinvigencia\r");
            lsb.Append("and usuar.dtfinvigencia>=getdate()\r");
            lsb.Append("and usuar.icodcatalogo = " + iCodUsuario + "\r");
            lsb.Append(")\r");
            lsb.Append("DECLARE @FechaInicio DATETIME = '2016-07-01 00:00:00.000'\r ");
            lsb.Append("DECLARE @FechaFin DATETIME = DATEADD (MONTH , 1, @FEchaInicio)\r ");
            lsb.Append("DECLARE @Top INT = 10\r");

            lsb.Append("SELECT\r");
            lsb.Append("Emple.NomCompleto as SYODisplayName,\r");
            lsb.Append("FInal.URI,");
            lsb.Append("FInal.TotalSegundos,\r");
            lsb.Append("FInal.Minutos,\r ");
            lsb.Append("FInal.Horas\r ");
            lsb.Append("FROM(\r");



            lsb.Append("SELECT TOP(@Top) URI, TotalSegundos,\r");
            lsb.Append("ceiling(convert(float,TotalSegundos)/60.00) AS Minutos,ceiling(Convert(float,ceiling(convert(float,TotalSegundos))/60.00)/60) Horas FROM \r");
            lsb.Append("(SELECT DescURI AS URI, SUM(Segundos) AS TotalSegundos FROM\r ");
            lsb.Append("(SELECT CDR.SYOUriDesc AS DescURI, SUM(CDR.SYODurationSec) AS Segundos FROM \r ");
            lsb.Append("K5SeeYouOn.[VisHistoricos('Client','Clientes','Español')] CLI\r ");
            lsb.Append("JOIN K5SeeYouOn.[vishistoricos('SYOUri','SYO Uris','Español')] URI\r ");
            lsb.Append("ON URI.Client = CLI.iCodCatalogo\r ");
            lsb.Append("JOIN K5SeeYouOn.[VisDetallados('Detall','DetalleCDRSeeYouOn','Español')] CDR\r ");
            lsb.Append("ON URI.iCodCatalogo = CDR.SYOUri \r ");
            lsb.Append("AND URI.dtinivigencia <> URI.dtfinvigencia AND URI.dtfinvigencia >= GETDATE()\r ");
            lsb.Append("AND CLI.dtinivigencia <> CLI.dtfinvigencia AND	CLI.dtfinvigencia >= GETDATE()");
            lsb.Append("AND CDR.SYOTime >='" + fechaInicio + "'");
            lsb.Append("AND CDR.SYOTime < = '" + fechaFin + "'");
            lsb.Append("AND URI.Client = @Cliente GROUP BY CLI.vchDescripcion, CDR.SYOUri, CDR.SYOUriDesc UNION\r");
            lsb.Append("SELECT CDR.SYODestinationNumber AS DescURI, SUM(CDR.SYODurationSec) AS Segundos\r ");
            lsb.Append("FROM K5SeeYouOn.[VisDetallados('Detall','DetalleCDRSeeYouOn','Español')] CDR\r ");
            lsb.Append("WHERE CDR.SYOTime >= @FechaInicio AND CDR.SYOTime < @FechaFin\r ");
            lsb.Append("AND CDR.SYODestinationNumber IN(SELECT CDR.SYOUriDesc FROM\r ");
            lsb.Append("K5SeeYouOn.[VisHistoricos('Client','Clientes','Español')] CLI\r ");
            lsb.Append("JOIN K5SeeYouOn.[vishistoricos('SYOUri','SYO Uris','Español')] URI\r ");
            lsb.Append("ON URI.Client = CLI.iCodCatalogo\r ");
            lsb.Append("JOIN K5SeeYouOn.[VisDetallados('Detall','DetalleCDRSeeYouOn','Español')] CDR\r ");
            lsb.Append("ON URI.iCodCatalogo = CDR.SYOUri AND URI.dtinivigencia <> URI.dtfinvigencia\r ");
            lsb.Append("AND URI.dtfinvigencia >= GETDATE() AND CLI.dtinivigencia <> CLI.dtfinvigencia\r ");
            lsb.Append("AND CLI.dtfinvigencia >= GETDATE()\r ");
            lsb.Append("AND CDR.SYOTime >='" + fechaInicio + "'");
            lsb.Append("AND CDR.SYOTime < = '" + fechaFin + "'");
            lsb.Append("AND URI.Client = @Cliente GROUP BY CDR.SYOUriDesc)GROUP BY\r");
            lsb.Append("CDR.SYODestinationNumber)UnionUOrdenarParaAgrupar\r");
            lsb.Append("GROUP BY DescURI)Final ORDER BY TotalSegundos DESC\r");

            lsb.Append(") FInal\r");
            lsb.Append("JOIN K5SeeYouOn.[vishistoricos('SYOUri','SYO Uris','Español')] U\r");
            lsb.Append("ON FInal.URI = U.vchDescripcion and\r");
            lsb.Append("U.dtinivigencia <> U.dtfinvigencia AND U.dtfinvigencia >= GETDATE()\r");
            lsb.Append("JOIN K5SeeYouOn.[VisHistoricos('Emple','Empleados','Español')] Emple\r");
            lsb.Append("ON Emple.icodcatalogo = U.Emple and\r");
            lsb.Append("Emple.dtinivigencia <> Emple.dtfinvigencia AND Emple.dtfinvigencia >= GETDATE()\r");
            return lsb.ToString();
        }
        public string ConsultaUsuariosConMenosUsoPorClienteSYO(int iCodUsuario, string fechaInicio, string fechaFin)
        {
            StringBuilder lsb = new StringBuilder();
            lsb.Append("DECLARE @Cliente VARCHAR(MAX) =(\r");
            lsb.Append("select Empre.Client from K5SeeYouOn.[vishistoricos('usuar','usuarios','español')] Usuar\r");
            lsb.Append("join K5SeeYouOn.[vishistoricos('Emple','Empleados','español')] Emple\r");
            lsb.Append("on Emple.dtinivigencia<>Emple.dtfinvigencia\r");
            lsb.Append("and Emple.dtfinvigencia>=getdate()\r");
            lsb.Append("and Emple.Usuar = Usuar.icodCatalogo\r");
            lsb.Append("join K5SeeYouOn.[vishistoricos('Empre','Empresas','español')] Empre\r");
            lsb.Append("on Empre.dtinivigencia<>Empre.dtfinvigencia\r");
            lsb.Append("and Empre.dtfinvigencia>=getdate()\r");
            lsb.Append("and Usuar.Empre = Empre.icodCatalogo\r");
            lsb.Append("where usuar.dtinivigencia<>usuar.dtfinvigencia\r");
            lsb.Append("and usuar.dtfinvigencia>=getdate()\r");
            lsb.Append("and usuar.icodcatalogo = " + iCodUsuario + "\r");
            lsb.Append(")\r");
            lsb.Append("DECLARE @FechaInicio DATETIME = '2016-07-01 00:00:00.000'\r ");
            lsb.Append("DECLARE @FechaFin DATETIME = DATEADD (MONTH , 1, @FEchaInicio)\r ");
            lsb.Append("DECLARE @Top INT = 10\r");

            lsb.Append("SELECT\r");
            lsb.Append("Emple.NomCompleto as SYODisplayName,\r");
            lsb.Append("FInal.URI,");
            lsb.Append("FInal.TotalSegundos,\r");
            lsb.Append("FInal.Minutos,\r ");
            lsb.Append("FInal.Horas\r ");
            lsb.Append("FROM(\r");




            lsb.Append("SELECT TOP(@Top) URI, TotalSegundos,\r");
            lsb.Append("ceiling(convert(float,TotalSegundos)/60.00) AS Minutos,ceiling(Convert(float,ceiling(convert(float,TotalSegundos))/60.00)/60) Horas FROM \r");
            lsb.Append("(SELECT DescURI AS URI, SUM(Segundos) AS TotalSegundos FROM(SELECT CDR.SYOUriDesc AS DescURI,\r ");
            lsb.Append("SUM(CDR.SYODurationSec) AS Segundos FROM \r ");
            lsb.Append("K5SeeYouOn.[VisHistoricos('Client','Clientes','Español')] CLI\r ");
            lsb.Append("JOIN K5SeeYouOn.[vishistoricos('SYOUri','SYO Uris','Español')] URI\r ");
            lsb.Append("ON URI.Client = CLI.iCodCatalogo JOIN\r ");
            lsb.Append("K5SeeYouOn.[VisDetallados('Detall','DetalleCDRSeeYouOn','Español')] CDR\r ");
            lsb.Append("ON URI.iCodCatalogo = CDR.SYOUri AND URI.dtinivigencia <> URI.dtfinvigencia\r ");
            lsb.Append("AND URI.dtfinvigencia >= GETDATE()\r ");
            lsb.Append("AND CLI.dtinivigencia <> CLI.dtfinvigencia AND	CLI.dtfinvigencia >= GETDATE()");
            lsb.Append("AND CDR.SYOTime >='" + fechaInicio + "'");
            lsb.Append("AND CDR.SYOTime < = '" + fechaFin + "'");
            lsb.Append("AND URI.Client = @Cliente GROUP BY CLI.vchDescripcion, CDR.SYOUri, CDR.SYOUriDesc UNION\r");
            lsb.Append("SELECT CDR.SYODestinationNumber AS DescURI, SUM(CDR.SYODurationSec) AS Segundos\r");
            lsb.Append("FROM K5SeeYouOn.[VisDetallados('Detall','DetalleCDRSeeYouOn','Español')] CDR\r");
            lsb.Append("WHERE CDR.SYOTime >= @FechaInicio AND CDR.SYOTime < @FechaFin\r ");
            lsb.Append("AND CDR.SYODestinationNumber IN(SELECT CDR.SYOUriDesc FROM\r ");
            lsb.Append("K5SeeYouOn.[VisHistoricos('Client','Clientes','Español')] CLI JOIN\r ");
            lsb.Append("K5SeeYouOn.[vishistoricos('SYOUri','SYO Uris','Español')]\r ");
            lsb.Append("URI ON URI.Client = CLI.iCodCatalogo\r ");
            lsb.Append("JOIN K5SeeYouOn.[VisDetallados('Detall','DetalleCDRSeeYouOn','Español')] CDR\r ");
            lsb.Append("ON URI.iCodCatalogo = CDR.SYOUri AND URI.dtinivigencia <> URI.dtfinvigencia\r ");
            lsb.Append("AND URI.dtfinvigencia >= GETDATE() AND\r ");
            lsb.Append("CLI.dtinivigencia <> CLI.dtfinvigencia AND CLI.dtfinvigencia >= GETDATE()\r ");
            lsb.Append("AND CDR.SYOTime >='" + fechaInicio + "'");
            lsb.Append("AND CDR.SYOTime < = '" + fechaFin + "'");
            lsb.Append("AND URI.Client = @Cliente GROUP BY CDR.SYOUriDesc)GROUP BY\r");
            lsb.Append("CDR.SYODestinationNumber)UnionUOrdenarParaAgrupar\r");
            lsb.Append("GROUP BY DescURI)Final ORDER BY TotalSegundos ASC\r");

            lsb.Append(") FInal\r");
            lsb.Append("JOIN K5SeeYouOn.[vishistoricos('SYOUri','SYO Uris','Español')] U\r");
            lsb.Append("ON FInal.URI = U.vchDescripcion and\r");
            lsb.Append("U.dtinivigencia <> U.dtfinvigencia AND U.dtfinvigencia >= GETDATE()\r");
            lsb.Append("JOIN K5SeeYouOn.[VisHistoricos('Emple','Empleados','Español')] Emple\r");
            lsb.Append("ON Emple.icodcatalogo = U.Emple and\r");
            lsb.Append("Emple.dtinivigencia <> Emple.dtfinvigencia AND Emple.dtfinvigencia >= GETDATE()\r");
            return lsb.ToString();
        }

        public string ConsultaServiciosPorClienteSYO(int iCodUsuario, string fechaInicio, string fechaFin)
        {
            StringBuilder lsb = new StringBuilder();
            lsb.Append("DECLARE @Cliente VARCHAR(MAX) =(\r");
            lsb.Append("select Empre.Client from K5SeeYouOn.[vishistoricos('usuar','usuarios','español')] Usuar\r");
            lsb.Append("join K5SeeYouOn.[vishistoricos('Emple','Empleados','español')] Emple\r");
            lsb.Append("on Emple.dtinivigencia<>Emple.dtfinvigencia\r");
            lsb.Append("and Emple.dtfinvigencia>=getdate()\r");
            lsb.Append("and Emple.Usuar = Usuar.icodCatalogo\r");
            lsb.Append("join K5SeeYouOn.[vishistoricos('Empre','Empresas','español')] Empre\r");
            lsb.Append("on Empre.dtinivigencia<>Empre.dtfinvigencia\r");
            lsb.Append("and Empre.dtfinvigencia>=getdate()\r");
            lsb.Append("and Usuar.Empre = Empre.icodCatalogo\r");
            lsb.Append("where usuar.dtinivigencia<>usuar.dtfinvigencia\r");
            lsb.Append("and usuar.dtfinvigencia>=getdate()\r");
            lsb.Append("and usuar.icodcatalogo = " + iCodUsuario + "\r");
            lsb.Append(")\r");
            lsb.Append("DECLARE @FechaInicio DATETIME = '2016-07-01 00:00:00.000'\r ");
            lsb.Append("DECLARE @FechaFin DATETIME = DATEADD (MONTH , 1, @FEchaInicio)\r ");
            lsb.Append("if object_id('tempdb..#ServiciosContratados') is not null \r");
            lsb.Append("begin \r ");
            lsb.Append("DROP TABLE #ServiciosContratados\r ");
            lsb.Append("end\r ");

            lsb.Append("CREATE TABLE #ServiciosContratados (\r");
            lsb.Append("ID INT IDENTITY(1,1) PRIMARY KEY,\r");
            lsb.Append("iCodCatalogo VARCHAR(MAX),\r");
            lsb.Append("NomCompleto VARCHAR(MAX),\r");
            lsb.Append("DisplayName VARCHAR(MAX),\r");
            lsb.Append("UserName VARCHAR(MAX),\r");
            lsb.Append("AddressPattern VARCHAR(MAX),\r");
            lsb.Append("URI VARCHAR(MAX),\r");
            lsb.Append("Registro INT\r");
            lsb.Append(")\r");
            lsb.Append("INSERT INTO #ServiciosContratados\r");
            lsb.Append("SELECT\r");
            lsb.Append("URI.iCodCatalogo as iCodCatalogo,\r");
            lsb.Append("Emple.NomCompleto,\r");
            lsb.Append("UPPER(URI.SYODisplayName) AS DisplayName,\r");
            lsb.Append("UPPER(URI.vchCodigo) AS UserName,\r");
            lsb.Append("UPPER(URI.SYOAddressPattern) AS AddressPattern,\r ");
            lsb.Append("URI.vchDescripcion AS URI,\r ");
            lsb.Append("COUNT(*) AS NumeroDe\r");
            lsb.Append("FROM\r ");
            lsb.Append("K5SeeYouOn.[vishistoricos('SYOUri','SYO Uris','Español')] URI\r ");
            lsb.Append("JOIN K5SeeYouOn.[VisHistoricos('Emple','Empleados','Español')] Emple\r ");

            lsb.Append("ON Emple.icodcatalogo = URI.Emple\r");
            lsb.Append("WHERE \r");
            lsb.Append("URI.dtinivigencia <> URI.dtfinvigencia\r");
            lsb.Append("AND URI.dtfinvigencia >= GETDATE()\r");
            lsb.Append("AND URI.Client = @Cliente\r");
            lsb.Append("GROUP BY URI.iCodCatalogo, URI.vchCodigo, URI.vchDescripcion, URI.SYODisplayName, URI.SYOAddressPattern, Emple.NomCompleto\r");
            lsb.Append("DECLARE @Maximo		INT = (SELECT COUNT(*) FROM #ServiciosContratados)\r");
            lsb.Append("DECLARE @contador	INT = 1\r");
            lsb.Append("WHILE (@contador <= @Maximo)\r");
            lsb.Append("BEGIN\r");
            lsb.Append("DECLARE @DATO VARCHAR(MAX) = (SELECT URI FROM #ServiciosContratados WHERE ID = @contador)\r");
            lsb.Append("DECLARE @NUME VARCHAR(MAX) = (\r");
            lsb.Append("SELECT \r");
            lsb.Append("COUNT(*)\r");
            lsb.Append("FROM\r ");
            lsb.Append("K5SeeYouOn.[VisHistoricos('Client','Clientes','Español')] CLI\r ");
            lsb.Append("JOIN K5SeeYouOn.[vishistoricos('SYOUri','SYO Uris','Español')] URI\r");
            lsb.Append("ON URI.Client = CLI.iCodCatalogo\r ");
            lsb.Append("JOIN K5SeeYouOn.[VisDetallados('Detall','DetalleCDRSeeYouOn','Español')] CDR\r ");
            lsb.Append("ON URI.iCodCatalogo = CDR.SYOUri\r ");

            lsb.Append("AND URI.dtinivigencia <> URI.dtfinvigencia\r");
            lsb.Append("AND URI.dtfinvigencia >= GETDATE()\r");
            lsb.Append("AND CLI.dtinivigencia <> CLI.dtfinvigencia\r");
            lsb.Append("AND	CLI.dtfinvigencia >= GETDATE()\r");
            lsb.Append("AND CDR.SYOTime >='" + fechaInicio + "'");
            lsb.Append("AND CDR.SYOTime < = '" + fechaFin + "'");
            lsb.Append("AND URI.Client = @Cliente\r");
            lsb.Append("AND (CDR.SYOSourceNumber = @DATO OR CDR.SYODestinationNumber = @DATO)\r");
            lsb.Append(")\r");
            lsb.Append("UPDATE #ServiciosContratados SET Registro = @NUME  WHERE ID = @contador\r");
            lsb.Append("SET @contador = @contador + 1\r");
            lsb.Append("END\r");
            lsb.Append("SELECT iCodCatalogo, NomCompleto as DisplayName, UserName, AddressPattern, URI, Registro FROM #ServiciosContratados ORDER BY Registro DESC\r");
            return lsb.ToString();
        }
        public string ConsultaDetalleDeLlamadasDeUriSYO(int iCodUsuario, string fechaInicio, string fechaFin, string registroUri)
        {
            StringBuilder lsb = new StringBuilder();
            lsb.Append("DECLARE @Cliente VARCHAR(MAX) =(\r");
            lsb.Append("select Empre.Client from K5SeeYouOn.[vishistoricos('usuar','usuarios','español')] Usuar\r");
            lsb.Append("join K5SeeYouOn.[vishistoricos('Emple','Empleados','español')] Emple\r");
            lsb.Append("on Emple.dtinivigencia<>Emple.dtfinvigencia\r");
            lsb.Append("and Emple.dtfinvigencia>=getdate()\r");
            lsb.Append("and Emple.Usuar = Usuar.icodCatalogo\r");
            lsb.Append("join K5SeeYouOn.[vishistoricos('Empre','Empresas','español')] Empre\r");
            lsb.Append("on Empre.dtinivigencia<>Empre.dtfinvigencia\r");
            lsb.Append("and Empre.dtfinvigencia>=getdate()\r");
            lsb.Append("and Usuar.Empre = Empre.icodCatalogo\r");
            lsb.Append("where usuar.dtinivigencia<>usuar.dtfinvigencia\r");
            lsb.Append("and usuar.dtfinvigencia>=getdate()\r");
            lsb.Append("and usuar.icodcatalogo = " + iCodUsuario + "\r");
            lsb.Append(")\r");
            lsb.Append("DECLARE @URI VARCHAR(MAX) = 'queretaro@vector.com.mx'\r ");
            lsb.Append("DECLARE @FechaInicio DATETIME = '2016-07-01 00:00:00.000'\r ");
            lsb.Append("DECLARE @FechaFin DATETIME = DATEADD (MONTH , 1, @FEchaInicio)  \r");
            lsb.Append("Declare @URI2 VARCHAR(MAX) = (select vchDescripcion from K5SeeYouOn.[vishistoricos('SYOUri','SYO Uris','Español')]  \r");
            lsb.Append("where iCodCatalogo= " + registroUri + " and dtinivigencia <> dtfinvigencia AND dtfinvigencia >= GETDATE()) \r");
            lsb.Append("SELECT UPPER(CLI.vchDescripcion) AS Cliente, SYOTime = CONVERT(VARCHAR,CDR.SYOTime,120), CDR.SYOSystemNameDesc, CDR.SYONetworkAddress, \r ");
            lsb.Append("CDR.SYODurationSec,CDR.SYODuration,CDR.SYOSourceNumber,CDR.SYOSourceAddress,CDR.SYODestinationNumber,CDR.SYODestinationAddress,CDR.SYOCallTypeDesc,\r ");
            lsb.Append("CDR.SYOBandwidth,SYOCauseCode = CONVERT(VARCHAR,CDR.SYOCauseCode,120),CDR.SYOMIBLog,CDR.SYOOwnerConference FROM\r ");
            lsb.Append("K5SeeYouOn.[VisHistoricos('Client','Clientes','Español')] CLI\r ");
            lsb.Append("JOIN K5SeeYouOn.[vishistoricos('SYOUri','SYO Uris','Español')] URI\r");
            lsb.Append("ON URI.Client = CLI.iCodCatalogo JOIN K5SeeYouOn.[VisDetallados('Detall','DetalleCDRSeeYouOn','Español')] CDR\r");
            lsb.Append("ON URI.iCodCatalogo = CDR.SYOUri AND URI.dtinivigencia <> URI.dtfinvigencia\r");
            lsb.Append("AND URI.dtfinvigencia >= GETDATE() AND CLI.dtinivigencia <> CLI.dtfinvigencia AND CLI.dtfinvigencia >= GETDATE()\r");
            lsb.Append("AND CDR.SYOTime >='" + fechaInicio + "'");
            lsb.Append("AND CDR.SYOTime <=  '" + fechaFin + "'");
            lsb.Append("AND URI.Client = @Cliente\r ");
            lsb.Append("AND (CDR.SYOSourceNumber = @URI2  OR CDR.SYODestinationNumber = @URI2 )\r ");
            return lsb.ToString();
        }
        public string ConsultaTendenciaAnualSYO(int iCodUsuario, string fechaInicio)
        {
            StringBuilder lsb = new StringBuilder();
            lsb.Append("SET LANGUAGE 'SPANISH' \r");
            lsb.Append("DECLARE @Cliente VARCHAR(MAX) =(\r");
            lsb.Append("select Empre.Client from K5SeeYouOn.[vishistoricos('usuar','usuarios','español')] Usuar\r");
            lsb.Append("join K5SeeYouOn.[vishistoricos('Emple','Empleados','español')] Emple\r");
            lsb.Append("on Emple.dtinivigencia<>Emple.dtfinvigencia\r");
            lsb.Append("and Emple.dtfinvigencia>=getdate()\r");
            lsb.Append("and Emple.Usuar = Usuar.icodCatalogo\r");
            lsb.Append("join K5SeeYouOn.[vishistoricos('Empre','Empresas','español')] Empre\r");
            lsb.Append("on Empre.dtinivigencia<>Empre.dtfinvigencia\r");
            lsb.Append("and Empre.dtfinvigencia>=getdate()\r");
            lsb.Append("and Usuar.Empre = Empre.icodCatalogo\r");
            lsb.Append("where usuar.dtinivigencia<>usuar.dtfinvigencia\r");
            lsb.Append("and usuar.dtfinvigencia>=getdate()\r");
            lsb.Append("and usuar.icodcatalogo = " + iCodUsuario + "\r");
            lsb.Append(")\r");
            lsb.Append("DECLARE @FechaInicio DATETIME = '" + fechaInicio + "'\r");
            lsb.Append("if object_id('tempdb..#ConsumoHistorico') is not null\r ");
            lsb.Append("begin\r");
            lsb.Append("DROP TABLE #ConsumoHistorico\r");
            lsb.Append("end\r");
            lsb.Append("CREATE TABLE #ConsumoHistorico( \r ");
            lsb.Append("No INT IDENTITY(1,1) PRIMARY KEY, \r ");
            lsb.Append("Mes VARCHAR(MAX), \r ");
            lsb.Append("Anterior VARCHAR(MAX), \r ");
            lsb.Append("Actual VARCHAR(MAX), \r");
            lsb.Append(") \r");
            lsb.Append("DECLARE @CONTADOR INT = 0 \r");
            lsb.Append("WHILE (@CONTADOR <= 11) \r");
            lsb.Append("BEGIN ");
            lsb.Append("DECLARE @MES VARCHAR(MAX) = (SELECT(DATENAME(MONTH,DATEADD(MONTH,@CONTADOR,@FechaInicio)) + ' ' +DATENAME(YEAR,@FechaInicio)) AS MES) ");
            lsb.Append("DECLARE @ANTERIOR VARCHAR(MAX) = ( \r ");
            lsb.Append("SELECT\r ");
            lsb.Append("ISNULL(SUM(Segundos),0) AS TotalSegundos \r");
            lsb.Append("FROM\r");
            lsb.Append("(\r ");
            lsb.Append("SELECT\r ");
            lsb.Append("SUM(CDR.SYODurationSec) AS Segundos\r");
            lsb.Append("FROM\r");
            lsb.Append("K5SeeYouOn.[VisHistoricos('Client','Clientes','Español')] CLI\r");
            lsb.Append("JOIN K5SeeYouOn.[vishistoricos('SYOUri','SYO Uris','Español')] URI\r ");
            lsb.Append("ON URI.Client = CLI.iCodCatalogo\r ");
            lsb.Append("JOIN K5SeeYouOn.[VisDetallados('Detall','DetalleCDRSeeYouOn','Español')] CDR\r ");
            lsb.Append("ON URI.iCodCatalogo = CDR.SYOUri\r ");
            lsb.Append("AND URI.dtinivigencia <> URI.dtfinvigencia\r");
            lsb.Append("AND URI.dtfinvigencia >= GETDATE()\r");
            lsb.Append("AND CLI.dtinivigencia <> CLI.dtfinvigencia\r");
            lsb.Append("AND	CLI.dtfinvigencia >= GETDATE()\r");
            lsb.Append("AND CDR.SYOTime >= (SELECT DATEADD(YEAR,-1, @MES))");
            lsb.Append("AND CDR.SYOTime < (SELECT DATEADD(YEAR,-1,DATEADD(MONTH,1, @MES)))");
            lsb.Append("AND URI.Client = @Cliente\r ");
            lsb.Append("GROUP BY CLI.vchDescripcion, CDR.SYOUri, CDR.SYOUriDesc\r ");
            lsb.Append("UNION\r");
            lsb.Append("SELECT\r");
            lsb.Append("SUM(CDR.SYODurationSec) AS Segundos\r ");
            lsb.Append("FROM K5SeeYouOn.[VisDetallados('Detall','DetalleCDRSeeYouOn','Español')] CDR\r ");
            lsb.Append("WHERE CDR.SYOTime >= (SELECT DATEADD(YEAR,-1, @MES))\r");
            lsb.Append("AND CDR.SYOTime < (SELECT DATEADD(YEAR,-1,DATEADD(MONTH,1, @MES)))\r");
            lsb.Append("AND CDR.SYODestinationNumber IN(\r");
            lsb.Append("SELECT\r ");
            lsb.Append("CDR.SYOUriDesc\r ");
            lsb.Append("FROM\r ");
            lsb.Append("K5SeeYouOn.[VisHistoricos('Client','Clientes','Español')] CLI\r ");
            lsb.Append("JOIN K5SeeYouOn.[vishistoricos('SYOUri','SYO Uris','Español')] URI\r");
            lsb.Append("ON URI.Client = CLI.iCodCatalogo\r");
            lsb.Append("JOIN K5SeeYouOn.[VisDetallados('Detall','DetalleCDRSeeYouOn','Español')] CDR\r");
            lsb.Append("ON URI.iCodCatalogo = CDR.SYOUri\r");
            lsb.Append("AND URI.dtinivigencia <> URI.dtfinvigencia\r");
            lsb.Append("AND URI.dtfinvigencia >= GETDATE()\r");
            lsb.Append("AND CLI.dtinivigencia <> CLI.dtfinvigencia\r ");
            lsb.Append("AND	CLI.dtfinvigencia >= GETDATE()\r ");
            lsb.Append("AND CDR.SYOTime >= (SELECT DATEADD(YEAR,-1, @MES))\r");
            lsb.Append("AND CDR.SYOTime < (SELECT DATEADD(YEAR,-1,DATEADD(MONTH,1, @MES)))\r");
            lsb.Append("AND URI.Client = @Cliente\r ");
            lsb.Append("GROUP BY CDR.SYOUriDesc\r ");
            lsb.Append(")\r");
            lsb.Append("GROUP BY CDR.SYODestinationNumber\r");
            lsb.Append(")Final\r");
            lsb.Append(") \r ");
            lsb.Append("DECLARE @ACTUAL VARCHAR(MAX) = ( \r ");
            lsb.Append("SELECT\r ");
            lsb.Append("ISNULL(SUM(Segundos),0) AS TotalSegundos\r ");
            lsb.Append("FROM\r");
            lsb.Append("(\r");
            lsb.Append("SELECT\r");
            lsb.Append("SUM(CDR.SYODurationSec) AS Segundos\r");
            lsb.Append("FROM\r");
            lsb.Append("K5SeeYouOn.[VisHistoricos('Client','Clientes','Español')] CLI\r");
            lsb.Append("JOIN K5SeeYouOn.[vishistoricos('SYOUri','SYO Uris','Español')] URI\r ");
            lsb.Append("ON URI.Client = CLI.iCodCatalogo\r ");
            lsb.Append("JOIN K5SeeYouOn.[VisDetallados('Detall','DetalleCDRSeeYouOn','Español')] CDR\r");
            lsb.Append("ON URI.iCodCatalogo = CDR.SYOUri\r");
            lsb.Append("AND URI.dtinivigencia <> URI.dtfinvigencia\r ");
            lsb.Append("AND URI.dtfinvigencia >= GETDATE()\r ");
            lsb.Append("AND CLI.dtinivigencia <> CLI.dtfinvigencia\r");
            lsb.Append("AND	CLI.dtfinvigencia >= GETDATE()\r");
            lsb.Append("AND CDR.SYOTime >= @MES\r");
            lsb.Append("AND CDR.SYOTime < (SELECT DATEADD(MONTH,1, @MES))\r ");
            lsb.Append("AND URI.Client = @Cliente\r ");
            lsb.Append("GROUP BY CLI.vchDescripcion, CDR.SYOUri, CDR.SYOUriDesc\r ");
            lsb.Append("UNION\r ");
            lsb.Append("SELECT\r");
            lsb.Append("SUM(CDR.SYODurationSec) AS Segundos\r");
            lsb.Append("FROM K5SeeYouOn.[VisDetallados('Detall','DetalleCDRSeeYouOn','Español')] CDR\r");
            lsb.Append("WHERE CDR.SYOTime >= @MES\r");
            lsb.Append("AND CDR.SYOTime < (SELECT DATEADD(MONTH,1, @MES))\r");
            lsb.Append("AND CDR.SYODestinationNumber IN(\r");
            lsb.Append("SELECT\r ");
            lsb.Append("CDR.SYOUriDesc\r ");
            lsb.Append("FROM\r");
            lsb.Append("K5SeeYouOn.[VisHistoricos('Client','Clientes','Español')] CLI\r");
            lsb.Append("JOIN K5SeeYouOn.[vishistoricos('SYOUri','SYO Uris','Español')] URI\r ");
            lsb.Append("ON URI.Client = CLI.iCodCatalogo\r ");
            lsb.Append("JOIN K5SeeYouOn.[VisDetallados('Detall','DetalleCDRSeeYouOn','Español')] CDR\r");
            lsb.Append("ON URI.iCodCatalogo = CDR.SYOUri\r");
            lsb.Append("AND URI.dtinivigencia <> URI.dtfinvigencia\r");
            lsb.Append("AND URI.dtfinvigencia >= GETDATE()\r ");
            lsb.Append("AND CLI.dtinivigencia <> CLI.dtfinvigencia\r ");
            lsb.Append("AND	CLI.dtfinvigencia >= GETDATE()\r ");
            lsb.Append("AND CDR.SYOTime >= @MES\r ");
            lsb.Append("AND CDR.SYOTime < (SELECT DATEADD(MONTH,1, @MES))\r");
            lsb.Append("AND URI.Client = @Cliente\r");
            lsb.Append("GROUP BY CDR.SYOUriDesc\r");
            lsb.Append(")\r");
            lsb.Append("GROUP BY CDR.SYODestinationNumber\r");
            lsb.Append(")Final\r");
            lsb.Append(")\r ");
            lsb.Append("INSERT INTO #ConsumoHistorico \r ");
            lsb.Append("VALUES(UPPER(@MES),@ANTERIOR,@ACTUAL)\r");
            lsb.Append("SET @CONTADOR = @CONTADOR + 1 \r");
            lsb.Append("END\r ");
            lsb.Append("SELECT  No, Mes, CEILING(CONVERT(FLOAT, ANTERIOR) / 60.00) As Anterior, CEILING(CONVERT(FLOAT, CONVERT(INT, Actual)) / 60.00) As Actual FROM #ConsumoHistorico\r ");
            return lsb.ToString();
        }
        public string ConsultaDetalleDeLlamadasUriUMTSYO(string fechaInicio, string fechaFin, string registroUri)
        {
            StringBuilder lsb = new StringBuilder();
            lsb.Append("Declare @URI2 VARCHAR(MAX) = (select vchDescripcion from K5SeeYouOn.[vishistoricos('SYOUri','SYO Uris','Español')]  \r");
            lsb.Append("where iCodCatalogo= " + registroUri + " and dtinivigencia <> dtfinvigencia AND dtfinvigencia >= GETDATE()) \r");
            lsb.Append("SELECT UPPER(CLI.vchDescripcion) AS Cliente, SYOTime = CONVERT(VARCHAR,CDR.SYOTime,120), CDR.SYOSystemNameDesc, CDR.SYONetworkAddress, \r ");
            lsb.Append("CDR.SYODurationSec,CDR.SYODuration,CDR.SYOSourceNumber,CDR.SYOSourceAddress,CDR.SYODestinationNumber,CDR.SYODestinationAddress,CDR.SYOCallTypeDesc,\r ");
            lsb.Append("CDR.SYOBandwidth,SYOCauseCode = CONVERT(VARCHAR,CDR.SYOCauseCode,120),CDR.SYOMIBLog,CDR.SYOOwnerConference FROM\r ");
            lsb.Append("K5SeeYouOn.[VisHistoricos('Client','Clientes','Español')] CLI\r ");
            lsb.Append("JOIN K5SeeYouOn.[vishistoricos('SYOUri','SYO Uris','Español')] URI\r");
            lsb.Append("ON URI.Client = CLI.iCodCatalogo JOIN K5SeeYouOn.[VisDetallados('Detall','DetalleCDRSeeYouOn','Español')] CDR\r");
            lsb.Append("ON URI.iCodCatalogo = CDR.SYOUri AND URI.dtinivigencia <> URI.dtfinvigencia\r");
            lsb.Append("AND URI.dtfinvigencia >= GETDATE() AND CLI.dtinivigencia <> CLI.dtfinvigencia AND CLI.dtfinvigencia >= GETDATE()\r");
            lsb.Append("AND CDR.SYOTime >='" + fechaInicio + "'");
            lsb.Append("AND CDR.SYOTime <=  '" + fechaFin + "'");
            lsb.Append("AND (CDR.SYOSourceNumber = @URI2  OR CDR.SYODestinationNumber = @URI2 )\r ");
            return lsb.ToString();
        }
        public string consultaConfiguracionDeReportesPorPerfil(int iCodPerfil)
        {
            StringBuilder lsb = new StringBuilder();

            lsb.Append("select  \n ");
            lsb.Append("[Reporte] = CveRep.Descripcion, \n ");
            lsb.Append("[Contenedor] = IDCtrl.Descripcion, \n ");
            lsb.Append("[tipoGrafDefault] = TpGraf.Descripcion, \n ");
            lsb.Append("[tituloGrid] = Cnfg.FCTituloTabla, \n ");
            lsb.Append("[tituloGrafica] = Cnfg.FCTituloGrafica, \n ");
            lsb.Append("[pestaniaActiva] = Cnfg.FCPestanaActiva \n ");
            lsb.Append("from " + DSODataContext.Schema + ".[VisHistoricos('FCConfReportes','FC Configuracion de reportes','Español')] Cnfg \n ");
            lsb.Append(" \n ");
            lsb.Append("Join " + DSODataContext.Schema + ".[VisHistoricos('FCCveRep','FC Clave de reporte','Español')] CveRep \n ");
            lsb.Append("on CveRep.iCodCatalogo = Cnfg.FCCveRep \n ");
            lsb.Append("and CveRep.dtIniVigencia <> CveRep.dtFinVigencia  \n ");
            lsb.Append("and CveRep.dtFinVigencia >= GETDATE() \n ");
            lsb.Append(" \n ");
            lsb.Append("Join " + DSODataContext.Schema + ".[VisHistoricos('FCIDControl','FC ID de control','Español')] IDCtrl \n ");
            lsb.Append("on IDCtrl.iCodCatalogo = Cnfg.FCIDControl \n ");
            lsb.Append("and IDCtrl.dtIniVigencia <> IDCtrl.dtFinVigencia  \n ");
            lsb.Append("and IDCtrl.dtFinVigencia >= GETDATE() \n ");
            lsb.Append(" \n ");
            lsb.Append("Join " + DSODataContext.Schema + ".[VisHistoricos('FCTipoGraf','FC Tipo de Grafica','Español')] TpGraf \n ");
            lsb.Append("on TpGraf.iCodCatalogo = Cnfg.FCTipoGraf \n ");
            lsb.Append("and TpGraf.dtIniVigencia <> TpGraf.dtFinVigencia  \n ");
            lsb.Append("and TpGraf.dtFinVigencia >= GETDATE() \n ");
            lsb.Append(" \n ");
            lsb.Append("Join " + DSODataContext.Schema + ".[VisHistoricos('FCDashboard','FC Dashboard','Español')] Dash \n ");
            lsb.Append("on Dash.iCodCatalogo = Cnfg.FCDashboard \n ");
            lsb.Append("and Dash.dtIniVigencia <> Dash.dtFinVigencia  \n ");
            lsb.Append("and Dash.dtFinVigencia >= GETDATE() \n ");
            lsb.Append(" \n ");
            lsb.Append("where Cnfg.dtIniVigencia <> Cnfg.dtFinVigencia  \n ");
            lsb.Append("and Cnfg.dtFinVigencia >= GETDATE() \n ");
            lsb.Append("and Cnfg.Perfil = " + iCodPerfil + " \n ");
            lsb.Append("and Dash.Descripcion = 'DashboardSYO.aspx' \n ");
            return lsb.ToString();
        }
    }
}
